batman-adv: compat: workaround for issues with make-kpkg for 4.5 kernels
Currently, batman-adv fails to build for 4.5 kernel headers provided by
Debian's make-kpkg. "make" complains with:

"include/net/sch_generic.h:413:2: error: implicit declaration of
function ‘G_TC_AT’ [-Werror=implicit-function-declaration]"

And:

"include/net/sch_generic.h:413:33: error: ‘AT_INGRESS’ undeclared (first
use in this function)"

The issue seems to be that make-kpkg creates two pkt_cls.h with the same
include guard but differing contents, "uapi/linux/pkt_cls.h" and
"linux/pkt_cls.h". The latter has its "#ifdef __KERNEL__" section
stripped and therefore misses the needed defines.

Depending on the include order, the batman-adv might fail.

This commit provides a workaround by ensuring that the full-blown
uapi variant is included first.

Eventually, the issue should be fixed in make-kpkg and this commit
reverted (no response from the make-kpkg Debian maintainer yet).

For future reference and updates:
* https://www.open-mesh.org/issues/322

Signed-off-by: Linus Lüssing <linus.luessing@c0d3.blue>